Feature/mysql
kishalayb18/eCommerce-3tier pull request #3
Opened 2024-03-03 06:48 UTC by HASH10DEV

please review

2024-03-03 08:02 UTC, kishalayb18 commented on deployments/cart/helm/.helmignore
> +# Patterns to ignore when building packages.
remove this file

2024-03-03 12:49 UTC, kishalayb18 requested changes
resolve the changes

2024-03-03 12:49 UTC, kishalayb18 commented on deployments/mysql/helm/template/deployment.yaml
> +  name: mysql
parameterized the hardcoded values

2024-03-03 12:49 UTC, kishalayb18 commented on deployments/mysql/helm/template/deployment.yaml
> +        # added for Istio
why is this required?

2024-03-03 12:49 UTC, kishalayb18 commented on deployments/mysql/helm/template/deployment.yaml
> +      restartPolicy: Always
remove the  affinity,  nodeSelector, tolerations blocks for now

2024-03-03 12:49 UTC, kishalayb18 commented on deployments/mysql/helm/template/service.yaml
> +spec:
provide the type as the NodePort

2024-03-03 12:49 UTC, kishalayb18 commented on deployments/mysql/helm/template/service.yaml
> +    port: 3306
### {{ .Values.service.ports.port }}

parameterize the values

2024-03-03 12:49 UTC, kishalayb18 commented on deployments/mysql/helm/values.yaml
> +  type: ClusterIP
modify the type to NodePort for now

2024-03-03 12:49 UTC, kishalayb18 commented on deployments/mysql/helm/values.yaml
> +  annotations: {}
remove the values which is not required

2024-03-04 07:13 UTC, HASH10DEV commented on deployments/mysql/helm/values.yaml
> +  type: ClusterIP
this is done

2024-03-04 07:21 UTC, HASH10DEV commented on deployments/mysql/helm/template/deployment.yaml
> +      restartPolicy: Always
this is done

2024-03-18 08:04 UTC, HASH10DEV commented on deployments/mysql/helm/values.yaml
> +  annotations: {}
done

2024-03-18 08:20 UTC, HASH10DEV commented on deployments/mysql/helm/template/deployment.yaml
> +  name: mysql
done

2024-03-18 08:21 UTC, HASH10DEV commented on deployments/mysql/helm/template/deployment.yaml
> +        # added for Istio
removed

2024-03-18 08:25 UTC, HASH10DEV commented on deployments/mysql/helm/template/service.yaml
> +    port: 3306
done

2024-03-18 08:33 UTC, HASH10DEV commented
hi kishalay ive made all the changes accordingly

2024-03-20 04:59 UTC, kishalayb18 requested changes
modify the files based on the feedback please

2024-03-20 04:59 UTC, kishalayb18 commented on deployments/mysql/helm/template/deployment.yaml
> +  name: {{ .values.appname }}
please resolve this
{{ .Values.appName }}

2024-03-20 04:59 UTC, kishalayb18 commented on deployments/mysql/helm/template/deployment.yaml
> +      service: {{ .values.appname }}
modify this to {{ .Values.appName }}

2024-03-20 04:59 UTC, kishalayb18 commented on deployments/mysql/helm/template/deployment.yaml
> +        service: {{ .values.appname }}
{{ .Values.appName }}

2024-03-20 04:59 UTC, kishalayb18 commented on deployments/mysql/helm/template/deployment.yaml
> +      - name: {{ .values.appname }}
{{ .Values.appName }}

2024-03-20 04:59 UTC, kishalayb18 commented on deployments/mysql/helm/template/deployment.yaml
> +        image: {{ .Values.containers.image.repo }}{{ .Values.containers.image.tag }}
there must be a colon
{{ .Values.containers.image.repo }}:{{ .Values.containers.image.tag }}

2024-03-20 04:59 UTC, kishalayb18 commented on deployments/mysql/helm/template/deployment.yaml
> +        {{- include "container.resources" . | nindent 8 -}}
has the resource been added to helpers file, please review

2024-03-31 09:39 UTC, kishalayb18 approved these changes
LGTM

2024-03-31 09:39 UTC, kishalayb18 commented on deployments/mysql/helm/template/ingress.yaml
> +apiVersion: networking.k8s.io/v1
this file is not required

2024-03-31 09:39 UTC, kishalayb18 commented on deployments/mysql/helm/values.yaml
> +    port: 8080
compare this with main repository

2024-03-31 09:39 UTC, kishalayb18 commented on deployments/mysql/helm/values.yaml
> +  resources:
compare this with main repository

2024-03-31 09:42 UTC, kishalayb18 commented
good to ship

2024-03-31 09:42 UTC, merged