Feature/payment
kishalayb18/eCommerce-3tier pull request #4
Opened 2024-03-27 09:16 UTC by HASH10DEV

please verify

2024-03-30 14:40 UTC, kishalayb18 requested changes
please review the suggested changes

2024-03-30 14:40 UTC, kishalayb18 commented on deployments/payment/helm/.helmignore
> +# Patterns to ignore when building packages.
remove this file

2024-03-30 14:40 UTC, kishalayb18 commented on deployments/payment/helm/templates/_helpers.tpl
> +    cpu: {{ (.Values.containers.resources.limits).cpu | default "500m" }}
compare the CPU memory with the main repository

2024-03-30 14:40 UTC, kishalayb18 commented on deployments/payment/helm/templates/deployment.yaml
> +          - name: INSTANA_AGENT_HOST
compare the env with the main repository

2024-03-30 14:40 UTC, kishalayb18 commented on deployments/payment/helm/templates/tests/test-connection.yaml
> +apiVersion: v1
why is this file required

2024-03-30 14:40 UTC, kishalayb18 commented on deployments/payment/helm/values.yaml
> +    port: 8080
compare the port numbers

2024-03-31 09:00 UTC, HASH10DEV commented on deployments/payment/helm/.helmignore
> +# Patterns to ignore when building packages.
resolved

2024-03-31 09:13 UTC, kishalayb18 commented
restructure the helm folder

2024-03-31 09:30 UTC, kishalayb18 approved these changes
LGTM

2024-03-31 09:32 UTC, merged